travis:
  secure:
    BINSTAR_TOKEN: g9qqQvW8s0cMGBPUxFRPU29f5h+if1SDS6AK7x+XuDTDxdryAPl4Oqr05Z7kdR79wo04GUUPxE93IKhLpLKkByDlho4cRggdBPTsfZ9fCAP3fshbP/O7pzHppVmnJUskHNLReKPxAQoibVfWLXMphrtKUCJ1DVjPWdPwtbv8p2txC6soHHKSX8ioJhpttM8SKGbeq2IXltPGk1fZ1A5h+rkaI4hP+eThcOMoYwO404EIYn1RNk8EcFITNyYc6WonOJk4DHCDZvyOjVjmC/rOXbw1T4NXqIfnN+fjsNwMofz4WL3FwvNMpbeqfxZN55Vf9B4sxAXDoEcrT1c4CBzUiY3D//i4hHxZcnfyyxdB8zz4PhRpxs+K0OBxmWE1DKBz0GDNjUU0ctEiJXfb93Zoda2lmW2e2t26X8pnb2Uopvg90Y7dKuPVaVwNK710g3urj2dQJNLd1wEVhrYIVHKasts/7ihQMcgT4VammuY4uTZWiYJo0oWQBQl7lhD1cU3cbAI3mSyWPUEUgrId6ZUclxwEQPS9onq1Db5hjlRuYemQHzZ+4oz1NOv0M5IuQuXPuqwUUed6+GdyzaCuVl7YF4W4EzuiQ0EkHPQj5E8W+AdtJWz/SsZd/ByNHRUJUtYz5tfvoCvN4o07wIwNzTe+lZVzJ9f5uzxek7ViOWiS7vQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
